/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab34;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mypc
 */
public class _LogFrame extends javax.swing.JFrame {

    ArrayList<_Log> lst;
    DefaultTableModel model;

    /**
     * Creates new form _LogFrame
     */
    public _LogFrame() {
        initComponents();
        lst = new ArrayList<>();
        model = (DefaultTableModel) tblLog.getModel();
        readDB();
        fillToTable();
    }

    public String getTrangThai(int bit) {
        if (bit == 0) {
            return "Xuất";
        } else {
            return "Nhập";
        }
    }
        String url = "jdbc:sqlserver://localhost:1433;databaseName=lab34";
    public void readDB() {
        try (Connection conn = DriverManager.getConnection(url, "sa", "123")) {
            System.out.println("Thành công");
            Statement st = conn.createStatement();
            String query = "Select * from _log";
            ResultSet rs = st.executeQuery(query);                    
            while (rs.next()) {
                lst.add(new _Log(rs.getInt(2), rs.getInt(3), getTrangThai(rs.getInt(4)), new BigInteger(rs.getString(5).substring(0, rs.getString(5).indexOf("."))), rs.getDate(6)));
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void fillToTable() {
        model.setRowCount(0);
        for (_Log log : lst) {
            model.addRow(new Object[]{log.getMaHL(), log.getSoLuong(), log.getTrangThai(), log.getGia(), log.getNgay()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLog = new javax.swing.JTable();
        btnNhapNhieu = new javax.swing.JButton();
        btnXuatIt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Nhật ký");

        tblLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HL", "Số lượng", "Trạng thái", "Giá", "Ngày"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLog);

        btnNhapNhieu.setText("3 Hành lý nhập nhiều nhất");
        btnNhapNhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapNhieuActionPerformed(evt);
            }
        });

        btnXuatIt.setText("3 Hành lý xuất ít nhất");
        btnXuatIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatItActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btnNhapNhieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXuatIt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapNhieu)
                    .addComponent(btnXuatIt))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapNhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapNhieuActionPerformed
        // TODO add your handling code here:
        String message="";
        try (Connection conn = DriverManager.getConnection(url, "sa", "123")) {
            System.out.println("Thành công");
            Statement st = conn.createStatement();
            String query="select top 3 MaHL,sum(soLuong)from _log group by MaHL,trangThai having trangThai=1 order by sum(soluong) desc";
            ResultSet rs = st.executeQuery(query);                    
            while (rs.next()) {
                message+=rs.getInt(1)+"-Nhập-"+rs.getInt(2)+"\n";
            }
            conn.close();
            JOptionPane.showMessageDialog(rootPane, message);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNhapNhieuActionPerformed

    private void btnXuatItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatItActionPerformed
        // TODO add your handling code here:
        String message="";
        try (Connection conn = DriverManager.getConnection(url, "sa", "123")) {
            System.out.println("Thành công");
            Statement st = conn.createStatement();
            String query="select top 3 MaHL,sum(soLuong)from _log group by MaHL,trangThai having trangThai=0 order by sum(soluong)";
            ResultSet rs = st.executeQuery(query);                    
            while (rs.next()) {
                message+=rs.getInt(1)+"-Xuất-"+rs.getInt(2)+"\n";
            }
            conn.close();
            JOptionPane.showMessageDialog(rootPane, message);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXuatItActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_LogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _LogFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapNhieu;
    private javax.swing.JButton btnXuatIt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLog;
    // End of variables declaration//GEN-END:variables
}
