/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab34;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mypc
 */
public class LuggerFrame extends javax.swing.JFrame {

    ArrayList<Lugger> lst;
    DefaultTableModel model;

    /**
     * Creates new form LuggerFrame
     */
    public LuggerFrame() {
        initComponents();
        model = (DefaultTableModel) tblLugger.getModel();
    }

    public void fillToTable() {
        model.setRowCount(0);
        for (Lugger lugger : lst) {
            model.addRow(new Object[]{lugger.getMaHL(), lugger.getTen(), lugger.getTrongLuong(), lugger.getSoLuong(), lugger.getGiaHienTai(), lugger.getNgayTao()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLugger = new javax.swing.JTable();
        btnReadDB = new javax.swing.JButton();
        btn5Gia = new javax.swing.JButton();
        btn5Ngay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Hành Lý");

        tblLugger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HL", "Tên", "Trọng lượng", "Số lượng", "Giá hiện tại", "Ngày tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLugger);

        btnReadDB.setText("Read DB");
        btnReadDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadDBActionPerformed(evt);
            }
        });

        btn5Gia.setText("5 bản ghi có giá cao nhất");
        btn5Gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5GiaActionPerformed(evt);
            }
        });

        btn5Ngay.setText("5 bản ghi có ngày tạo lâu nhất");
        btn5Ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5NgayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnReadDB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5Gia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5Ngay)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReadDB)
                    .addComponent(btn5Gia)
                    .addComponent(btn5Ngay))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        String url = "jdbc:sqlserver://localhost:1433;databaseName=lab34";

    private void btnReadDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadDBActionPerformed
        // TODO add your handling code here:
        try (Connection conn = DriverManager.getConnection(url, "sa", "123")) {
            lst = new ArrayList<>();
            System.out.println("Thành công");
            Statement st = conn.createStatement();
            String query = "Select * from Lugger";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                lst.add(new Lugger(rs.getInt(1), rs.getString(2), rs.getFloat(3), rs.getInt(4), new BigDecimal(rs.getString(5)), rs.getDate(6)));
            }
            fillToTable();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReadDBActionPerformed

    private void btn5GiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5GiaActionPerformed
        // TODO add your handling code here:
        try (Connection conn = DriverManager.getConnection(url, "sa", "123")) {
            lst = new ArrayList<>();
            System.out.println("Thành công");
            Statement st = conn.createStatement();
            String query = "Select top 5 * from Lugger order by giaHienTai desc";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                lst.add(new Lugger(rs.getInt(1), rs.getString(2), rs.getFloat(3), rs.getInt(4), new BigDecimal(rs.getString(5)), rs.getDate(6)));
            }
            fillToTable();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn5GiaActionPerformed

    private void btn5NgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5NgayActionPerformed
        // TODO add your handling code here:
        try (Connection conn = DriverManager.getConnection(url, "sa", "123")) {
            lst = new ArrayList<>();
            System.out.println("Thành công");
            Statement st = conn.createStatement();
            String query = "Select top 5 * from Lugger order by DATEDIFF(day,ngayTao,GETDATE()) desc";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                lst.add(new Lugger(rs.getInt(1), rs.getString(2), rs.getFloat(3), rs.getInt(4), new BigDecimal(rs.getString(5)), rs.getDate(6)));
            }
            fillToTable();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn5NgayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LuggerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LuggerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LuggerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LuggerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuggerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn5Gia;
    private javax.swing.JButton btn5Ngay;
    private javax.swing.JButton btnReadDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLugger;
    // End of variables declaration//GEN-END:variables
}
